(function(w){String.prototype.format=function(){for(var temS=this,i=0;i<arguments.length;++i){temS=temS.replace(new RegExp("\\{"+i+"\\}","g"),arguments[i]);}
    return temS;}
    String.prototype.setCookie=function(value,expiryDays,domain,path,secure){if(this.length==0){return;}
        var builder=[this,"=",escape(value)];if(expiryDays){var date=new Date();date.setTime(date.getTime()+(expiryDays*86400000));builder.push(";expires=");builder.push(date.toUTCString());}
        if(domain){builder.push(";domain=");builder.push(domain);}
        if(path){builder.push(";path=");builder.push(path);}
        if(secure){builder.push(";secure");}
        document.cookie=builder.join("");};String.prototype.getCookie=function(){if(this.length==0){return'';}
        var re=new RegExp('\\b'+this+'\\s*=\\s*([^;]*)','i');var match=re.exec(document.cookie);return(match&&match.length>1?unescape(match[1]):'');};function StringBuilder(){this.strings=new Array();}
    StringBuilder.prototype.append=function(str){this.strings.push(str);return this;};StringBuilder.prototype.toString=function(){return this.strings.join("");};var GeneralRegs={alipay:/^(([a-zA-Z0-9])+([a-zA-Z0-9_\.\-])*\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4}))|(0{0,1}1[34578]{1}[0-9]{9})$/ig,bankaccount:/^([a-zA-Z0-9]|-)+$/ig,blank:/^\s*$/,cellphone:/^0{0,1}1[34578]{1}[0-9]{9}$/ig,email:/^([a-zA-Z0-9])+([a-zA-Z0-9_\.\-])*\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})$/ig,icard:/^(\d{18}|\d{15}|\d{17}x)$/ig,ihkcard:/^[a-z0-9]{1}\d{6,7}[a-z0-9]{1}$/ig,itwcard:/^[a-z]{1}\d{8,}$/ig,uname:/^[\u4e00-\u9fa5a-zA-Z\s]+$/ig,url:/^(http(s)?:\/\/)?[A-Za-z0-9]+\.[A-Za-z0-9]+[\/=\?%\-&_~`@[\]\':+!]*([^<>\"\"])*$/ig,vercode:/^\d{6}$/};var FLNS={"register":function(){var a=arguments,o=null,i,j,d,rt;for(i=0;i<a.length;++i){d=a[i].split(".");rt=d[0];eval('if (typeof '+rt+' == "undefined"){'+rt+' = {add: function (k, v) { if (!this[k]) { this[k] = v;} return this;} };} o = '+rt+';');for(j=1;j<d.length;++j){o[d[j]]=o[d[j]]||{};o=o[d[j]];o.add=function(k,v){if(!this[k]){this[k]=v;}return this;};}}
        return o;}};var InputValidation={"isNumber":function(intArg){return Object.prototype.toString.call(intArg)==="[object Number]";},"isEmail":function(emailStr){GeneralRegs.email.lastIndex=0;return GeneralRegs.email.test(emailStr);},"isName":function(nameStr){GeneralRegs.uname.lastIndex=0;return GeneralRegs.uname.test(nameStr);},"isUrl":function(urlStr){GeneralRegs.url.lastIndex=0;return GeneralRegs.url.test(urlStr);},"isPhone":function(phoneArg){GeneralRegs.cellphone.lastIndex=0;return GeneralRegs.cellphone.test(phoneArg);},"isIcard":function(icardArg){GeneralRegs.icard.lastIndex=0;return GeneralRegs.icard.test(icardArg);},"isAlipay":function(alipaydArg){GeneralRegs.alipay.lastIndex=0;return GeneralRegs.alipay.test(alipaydArg);},"isBankaccount":function(bankaccountdArg){GeneralRegs.bankaccount.lastIndex=0;return GeneralRegs.bankaccount.test(bankaccountdArg);}};w.StringBuilder=StringBuilder;w.InputValidation=InputValidation;w.GeneralRegs=GeneralRegs;w.FLNS=FLNS;})(window);(function(){$.extend(FLNS.register("Fanli"),{"Class":function(parent){var klass=function(){this.init.apply(this,arguments);};if(parent){var subclass=function(){};subclass.prototype=parent.prototype;klass.prototype=new subclass();}
    klass.prototype.init=function(){};klass.fn=klass.prototype;klass.fn.parent=klass;klass.extend=function(obj){var extended=obj.extended;for(var i in obj){klass[i]=obj[i];}
        if(extended)extended(klass);};klass.inculde=function(obj){var included=obj.included;for(var i in obj){klass.fn[i]=obj[i];}
        if(included)included(klass);};klass.proxy=function(func){var self=this;return(function(){return func.apply(self,arguments);});};klass.fn.proxy=klass.proxy;return klass;}});$.extend(FLNS.register("Fanli.Utility"),{"random":function(n){var uid=Math.random().toString(16).substr(2,n);while(uid.length<n){uid=Math.random().toString(16).substr(2,n);}
    return uid;},"guid":function(){return'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(c){var r=Math.random()*16|0,v=c=='x'?r:(r&0x3|0x8);return v.toString(16);}).toUpperCase();},"staticTimeStamp":function(t){var getTime=new Date().getTime();var returnts=parseInt(getTime/300000);var currentScriptPath=$('link[rel=stylesheet]').eq(0).attr('href');if(t){returnts=parseInt(getTime/(60*1000*t));}
else if(typeof(currentScriptPath)!=="undefined"){var timeStampArr=currentScriptPath.match(/^.*[\?\&](\d+\_\d+){1}$/i);if(timeStampArr){returnts=timeStampArr[1];}}
    return returnts;},"isLogin":"prouserid".getCookie()>0,"rootDomain":(function(){var tryExecLocation=/^.*?(\.(?:51)?fanli\.com)$/ig.exec(location.hostname);var rootDomain=".fanli.com";if(tryExecLocation){rootDomain=tryExecLocation[1];}
    return rootDomain;}()),"gtAppVersion":function(comparedVer){var ua=navigator.userAgent.toLocaleLowerCase();var uaReg=/^fanli(?:-super)?\/(.*) \(/ig;var tryRegExec=uaReg.exec(ua)||/(?:c_v=)([^&]*)/gi.exec(location.search);var actualVerArr;var comparedVerArr;var av1,av2,av3,av4;var cv1,cv2,cv3,cv4;if(!comparedVer||!tryRegExec){return false;}
    comparedVerArr=comparedVer.split(".");actualVerArr=tryRegExec[1].split(".");if(comparedVerArr.length<4||actualVerArr.length<4){return false;}
    av1=parseInt(actualVerArr[0]);av2=parseInt(actualVerArr[1]);av3=parseInt(actualVerArr[2]);av4=parseInt(actualVerArr[3]);cv1=parseInt(comparedVerArr[0]);cv2=parseInt(comparedVerArr[1]);cv3=parseInt(comparedVerArr[2]);cv4=parseInt(comparedVerArr[3]);if(((isNaN(av1)?0:(av1*100000000))+
        (isNaN(av2)?0:(av2*1000000))+
        (isNaN(av3)?0:(av3*10000))+
        (isNaN(av4)?0:av4))>=((isNaN(cv1)?0:(cv1*100000000))+
        (isNaN(cv2)?0:(cv2*1000000))+
        (isNaN(cv3)?0:(cv3*10000))+
        (isNaN(cv4)?0:cv4))){return true;}else{return false;}},bridgeApp:function(ifanliurl){var iframe=document.createElement("iframe");var iframeStyle=document.createAttribute("style");var iframeSrc=document.createAttribute("src");iframeStyle.nodeValue="display:none;width:0;height:0;";iframeSrc.nodeValue=ifanliurl;iframe.setAttributeNode(iframeStyle);iframe.setAttributeNode(iframeSrc);document.body.appendChild(iframe);setTimeout(function(){document.body.removeChild(iframe);},250);},"currentDomain":document.domain});$.extend(FLNS.register("Device.Utility"),{"Browser":{versions:(function(){var u=navigator.userAgent,app=navigator.appVersion;return{trident:u.indexOf('Trident')>-1,presto:u.indexOf('Presto')>-1,webkit:u.indexOf('AppleWebKit')>-1,gecko:u.indexOf('Gecko')>-1&&u.indexOf('KHTML')==-1,mobile:!!u.match(/AppleWebKit.*Mobile.*/),ios:!!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/),android:u.indexOf('Android')>-1||u.indexOf('Linux')>-1,iPhone:u.indexOf('iPhone')>-1,iPad:u.indexOf('iPad')>-1,webapp:u.indexOf('Safari')==-1,fanliapp:u.indexOf('Fanli')>-1};})(),language:(navigator.browserLanguage||navigator.language).toLowerCase()}});if(!'FirstUrl'.getCookie()){var ref=(!!document.referrer&&document.referrer.match(/:\/\/(.[^/]+)/)[1].indexOf('fanli.com')<0)?document.referrer:"http://m{0}/".format(Fanli.Utility.rootDomain);'FirstUrl'.setCookie(ref,'',Fanli.Utility.rootDomain,'/');}
    if(!'LandingUrl'.getCookie()){'LandingUrl'.setCookie(window.location.href,'',Fanli.Utility.rootDomain,'/');}}());(function(){FLNS.register("Fanli.Utility.Toast").add("open",function(content){var $toast=$("#J_singleton_toast");var toastOnClass="text-toast-on";if($toast.length==0){$toast=$('<div id="J_singleton_toast" class="text-toast"></div>').appendTo('body');}
    $toast.html(content).removeClass(toastOnClass);setTimeout(function(){$toast.css({marginLeft:Math.round(($(window).width()-($toast.outerWidth?$toast.outerWidth():$toast.width()))/2)+'px'}).addClass(toastOnClass);},0);});}());window.onpageshow=function(event){if(event.persisted){window.location.reload();}};var currentRootDomain=Fanli.Utility.rootDomain;var verifyCodeImageUrl="http://fun{0}/verify.png?".format(currentRootDomain);var currentApiRoot="http://m{0}/".format(currentRootDomain);var currentAppDomain="m{0}".format(currentRootDomain);var ifanliProtocol="m.51fanli.com";;(function(exports){var traceCrossPageCookie="__fl_trace_cpc";var tid='xxxxxxxx-xxxx-xxxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(c){var r=Math.random()*16|0,v=c=='x'?r:(r&0x3|0x8);return v.toString(16);}).toUpperCase();var domain=(function(){var tryExecLocation=/^.*?(\.(?:51)?fanli\.com)$/ig.exec(location.hostname);var rootDomain=".fanli.com";if(tryExecLocation){rootDomain=tryExecLocation[1];}
    return rootDomain;}());var urlReg=/^(?:(?:http(?:s)?:\/\/)?[A-Za-z0-9]+\.[A-Za-z0-9]+[\/=\?%\-&_~`@[\]\':+!]*([^<>\"\"])|(?:\/.*))*$/ig;var CookieOperation=(function(){function _setCookie(name,value,expiryDays,domain,path,secure){var builder=[name,"=",escape(value)];if(expiryDays){var date=new Date();date.setTime(date.getTime()+(expiryDays*86400000));builder.push(";expires=");builder.push(date.toUTCString());}
    if(domain){builder.push(";domain=");builder.push(domain);}
    if(path){builder.push(";path=");builder.push(path);}
    if(secure){builder.push(";secure");}
    document.cookie=builder.join("");}
    function _getCookie(name){var re=new RegExp('\\b'+name+'\\s*=\\s*([^;]*)','i');var match=re.exec(document.cookie);return(match&&match.length>1?unescape(match[1]):'');}
    return{setCookie:_setCookie,getCookie:_getCookie};}());var StringOperation={format:function(s,args){for(var i=0;i<args.length;++i){s=s.replace(new RegExp("\\{"+i+"\\}","g"),args[i]);}
    return s;},isUrl:function(url){if(!url){return false;}
    urlReg.lastIndex=0;url=url.toString();return urlReg.test(url);}};var ptid=CookieOperation.getCookie(traceCrossPageCookie);exports.UBT={isObject:function(obj){return Object.prototype.toString.call(obj)==="[object Object]";},uswitch:true,commonData:{referrer:encodeURIComponent(document.referrer),resolution_h:window.screen.height||0,resolution_v:window.screen.width||0,resolution_r:window.devicePixelRatio||1,language:navigator.language||navigator.userLanguage,url:encodeURIComponent(location.href)},mergeData:function(options){var dataObj=this.commonData;if(this.isObject(options)){for(var k in options){if(options.hasOwnProperty(k)){dataObj[k]=options[k];}}}
    return this;},_sendUrl:StringOperation.format("//eagle{0}/ubt.php",[domain]),_sendPV:function(){var builder=[];var dataObj=this.commonData;for(var j in dataObj){if(dataObj.hasOwnProperty(j)){builder.push(StringOperation.format("{0}={1}",[j,dataObj[j]]));}}
    builder.push("eventtype=pv");this._buildTrackImg(builder.join("&"));},track:function(){if(!this.uswitch){return;}
    var tArr=[];var builder=[];for(var i=0,length=arguments.length;i<length;i++){tArr.push([arguments[i]]);}
    builder.push("evttype=cd");builder.push(StringOperation.format("spm={0}",[encodeURIComponent(tArr.join("."))]));this._buildTrackImg(builder.join("&"));return false;},_buildTrackImg:function(parastr){var img=new Image();var userid=CookieOperation.getCookie("prouserid");var utmo=CookieOperation.getCookie("__utmo");var utmp=CookieOperation.getCookie("__utmp");var utmt=CookieOperation.getCookie("__utmt");var defaultParameterArr=[];if(utmo){defaultParameterArr.push("utmo="+utmo);}
    if(utmp){defaultParameterArr.push("utmp="+utmp);}
    if(utmt){defaultParameterArr.push("utmt="+utmt);}
    if(userid){defaultParameterArr.push("userid="+userid);}
    defaultParameterArr.push("tid="+tid);if(ptid){defaultParameterArr.push("ptid="+ptid);}
    defaultParameterArr.push("timestamp="+new Date().getTime());img.onload=img.onerror=function(){img.onload=img.onerror=null;}
    img.src=this._sendUrl+"?"+parastr+"&"+defaultParameterArr.join("&");},PlugIns:{clickOperation:function(options){var timeId;$(document).on("click","a, button, i, span, input[type=button], input[type=submit], .J_fanli_ubt_trigger",function(ev){var $this=$(this);var $ancestor=$this.parents();var ancestorLen=$ancestor.length;var temArr=[];var traceStr="";var parameterArr=[];var $module=$this.closest(".J_ubt_module");var module=$module.length>0&&$module.data("spm");var ubtindex=$this.data("ubtindex");var tagName=$this[0].tagName;var dataId=$this.data("id");var elementId=$this.attr("id");var klass=$.trim($this.attr("class")||"");var href=$this.attr("href");var text=$.trim($this.attr("data-ubttext")||$this.text()||"");var val=$this.val();var spm=$this.data("spm")||"";if(StringOperation.isUrl(href)&&href.indexOf("spm")==-1&&spm){if(-1==href.indexOf('#')){href=StringOperation.format("{0}{1}spm={2}",[href,(href.indexOf('?')===-1)?"?":"&",spm]);}
else{var href_split=href.split('#');href=StringOperation.format("{0}{1}spm={2}#{3}",[href_split[0],(href.indexOf('?')===-1)?"?":"&",spm,href_split[1]]);}
    $this.attr("href",href);}
    parameterArr.push("evttype=click");if(href&&href!="javascript:void(0);"&&href!="javascript:void(0)"){parameterArr.push("href="+encodeURIComponent(href));}
    if(spm){parameterArr.push("spm="+spm);}
    if(module){parameterArr.push("module="+module);}
    if(ubtindex){parameterArr.push("index="+ubtindex);}
    parameterArr.push("depth="+Math.round(($(window).scrollTop()/$(document).height())*100));temArr.push(tagName);if(dataId){temArr.push(StringOperation.format("[data-id={0}]",[dataId]));}
    if(href){temArr.push(StringOperation.format("[href={0}]",[href]));}
    if(elementId){temArr.push(StringOperation.format("[id={0}]",[elementId]));}
    if(klass){temArr.push(StringOperation.format("[class={0}]",[klass]));}
    if(text){temArr.push(StringOperation.format("[text={0}]",[text]));}
    if(val){temArr.push(StringOperation.format("[value={0}]",[val]));}
    traceStr+=temArr.join("");temArr.length=0;for(var i=0;i<ancestorLen;i++){var $currentNode=$ancestor.eq(i);var currentNode=$ancestor.get(i);var id=$currentNode.attr("id");var klass=$.trim($currentNode.attr("class")||"");var tagName=currentNode.tagName;if(tagName=="HTML"||tagName=="BODY"){break;}
        temArr.push(tagName);if(id){temArr.push(StringOperation.format("[id={0}]",[id]));}
        if(klass){temArr.push(StringOperation.format("[class={0}]",[klass]));}
        if(i>=5-1){break;}
        traceStr+="_"+temArr.join("");temArr.length=0;}
    parameterArr.push("evt=click_"+encodeURIComponent(traceStr));if(timeId){clearTimeout(timeId);}
    timeId=setTimeout(function(){UBT._buildTrackImg(parameterArr.join("&"));},25);});return UBT.PlugIns;},scrollOperation:function(){var $w=$(window);var sid;var parameterArr=[];$w.on("scroll",function(ev){if(sid){clearTimeout(sid);}
    sid=setTimeout(function(){parameterArr.push("spm="+Math.round(($w.scrollTop()/$(document).height())*100));parameterArr.push("evttype=scroll");UBT._buildTrackImg(parameterArr.join("&"));parameterArr.length=0;},800);});return UBT.PlugIns;}},init:function(){this._sendPV();CookieOperation.setCookie(traceCrossPageCookie,tid,"",domain,"/");return this;}};}(this));(function(){if(UBT.uswitch){UBT.mergeData(typeof fgv!="undefined"&&fgv.fanlitrace?fgv.fanlitrace:{}).init();UBT.PlugIns.clickOperation().scrollOperation();}}());;Function.prototype.method=function(name,fn){if(typeof this.prototype[name]=="undefined")this.prototype[name]=fn;};!String.prototype.trim&&String.method("trim",function(){return this.replace(/^\s+|\s+$/g,'');});!Function.prototype.bind&&Function.method("bind",function(oThis){if(typeof this!=="function"){throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");}
    var aArgs=Array.prototype.slice.call(arguments,1),fToBind=this,fNOP=function(){},fBound=function(){return fToBind.apply(this instanceof fNOP&&oThis?this:oThis,aArgs.concat(Array.prototype.slice.call(arguments)));};fNOP.prototype=this.prototype;fBound.prototype=new fNOP();return fBound;});String.method("format",function(){for(var s=this,i=0;i<arguments.length;++i){s=s.replace(new RegExp("\\{"+i+"\\}","g"),arguments[i]);}
    return s;});function StringBuilder(){this.strings=new Array();}
StringBuilder.prototype.append=function(str){this.strings.push(str);return this;};StringBuilder.prototype.toString=function(){return this.strings.join("");};var FMU={namespace:function(){var a=arguments,o=null,i,j,d,rt;for(i=0;i<a.length;++i){d=a[i].split(".");rt=d[0];if(typeof window[rt]=="undefined"){window[rt]={prop:function(k,v,c){if(!this[k]){this[k]=v;}
    return!c?this:this[k];}};}
    o=window[rt];for(j=1;j<d.length;++j){o[d[j]]=o[d[j]]||{};o=o[d[j]];o.prop=function(k,v,c){if(!this[k]){this[k]=v;}
        return!c?this:this[k];};}}
    return o;},Class:function(parent){var klass=function(){this.init.apply(this,arguments);};if(parent){var subclass=function(){};subclass.prototype=parent.prototype;klass.prototype=new subclass();}
    if(!klass.prototype.init){klass.prototype.init=function(){};}
    klass.fn=klass.prototype;klass.fn.parent=klass;klass.extend=function(obj){var extended=obj.extended;for(var i in obj){klass[i]=obj[i];}
        if(extended){extended(klass);}};klass.include=function(obj){var included=obj.included;for(var i in obj){klass.fn[i]=obj[i];}
        if(included){included(klass);}};klass.proxy=function(func){var self=this;return(function(){return func.apply(self,arguments);});};klass.fn.proxy=klass.proxy;$.extend(klass,{hookPlugin:function(fn){if($.isPlainObject(fn)){$.extend(this.fn,fn);}}});return klass;},prop:function(k,v,c){if(!this[k]){this[k]=v;}
    return!c?this:this[k];}};;(function(){FMU.UI.Base=new FMU.Class();FMU.UI.Base.include({eventNamespace:".FMUEVENT",destroy:function(){$("a,button,input").off(this.eventNamespace);}});FMU.UI.prop("define",function(name,protypes,superclass){if(typeof superclass!="function"){superclass=this.Base;}
    protypes=protypes||{};FMU.UI.prop(name,new FMU.Class(superclass),true).include(protypes);});}(FMU.namespace("FMU.UI")));;FMU.UI.define("Countdown",{init:function(){this.$output="";this.type="all",this.daySelector=".J_day";this.hourSelector=".J_hour";this.minuteSelector=".J_minute";this.secondSelector=".J_second";this.dhMerge=false;this.onExpiry=$.noop;this.showZeroDay=false;},setup:function(){var $output=this.$output;this.remain=parseInt($output.data("remain"),10);if(!$output||!this.remain){return;}
    this.$day=$(this.daySelector,$output);this.$hour=$(this.hourSelector,$output);this.$minute=$(this.minuteSelector,$output);this.$second=$(this.secondSelector,$output);this.start();},start:function(){this.run();this.intervalId=setInterval(this.proxy(function(){this.run();}),1*1000);},run:function(){if(this.remain<0){this.stop();return;}
    this.get();this.remain--;},pause:function(){clearInterval(this.intervalId);},stop:function(){this.pause();this.remain=-1;this.onExpiry();},reset:function(){this.pause();this.start();},get:function(){switch(this.type){case"all":this.getAll();break;case"day":this.$day.html(this.getDay());break;case"hour":this.$hour.html(this.getHour());break;case"minute":this.$minute.html(this.getMinute());break;case"second":this.$second.html(this.getSecond());break;default:this.getAll();break;}},getAll:function(){var d=this.getDay();var h=this.getHour();var m=this.getMinute();var s=this.getSecond();if(!this.dhMerge){if(!this.showZeroDay&&d==0){this.$day.parent().remove();}else{this.$day.html(d);}
    this.$hour.html(h);}else{this.$day.parent().remove();this.$hour.html(this.fillZero(parseInt(d)*24+parseInt(h),2));}
    this.$minute.html(m);this.$second.html(s);},getDay:function(){var day=parseInt(this.remain/86400,10);return day!==0?day:0;},getHour:function(){var hour=parseInt((this.remain%86400)/3600,10);if(this.type==="hour"){hour=parseInt(this.getDay()*24+(this.remain%86400)/3600,10);}
else{hour=this.fillZero(hour,2);}
    return hour;},getMinute:function(){var minute=parseInt((this.remain%3600)/60,10);if(this.type==="minute"){minute=parseInt(this.getDay()*24*60+this.getHour()*60+(this.remain%3600)/60,10);}
else{minute=this.fillZero(minute,2);}
    return minute;},getSecond:function(){var second=this.remain%60;if(this.type==="second"){second=this.getDay()*24*60*60+
    this.getHour()*60*60+
    this.getMinute()*60+
    this.remain%60;}
else{second=this.fillZero(second,2);}
    return second;},fillZero:function(num,digit){var str=''+num;while(str.length<digit){str='0'+str;}
    return str;}});;FMU.UI.define("Dialog",{init:function(){this.position='center';this.animation=false;this.closeSelector='.J_fmu_dl_close';this.maskClass='fmu-dl-mask';this.maskClose=false;this.opened=false;this.stepContainerSelector='.J_fmu_dl_step';this.goNextStepSelector='.J_fmu_dl_gonext';this.$dialog=$('#J_fmu_dl');this.eventNamespace='.CLOSEDL';this.render=false;this.confirmHandler=$.noop;this.autoClose=false;},setup:function(){if(this.render=="alert"){this._buildDefaultTemplate();}else if(this.render=="confirm"){this._buildDefaultTwoTemplate();}
    if(this.$dialog.length==0){return;}
    var $win=$(window),$dialog=this.$dialog,$mask=$('.{0}'.format(this.maskClass));this._step();this.$mask=$mask.length>0?$mask:$('<section class="{0}" style="display:none"></section>'.format(this.maskClass)).appendTo('body');this.$mask.add($dialog).on('touchmove',function(e){e.preventDefault();});$win.resize(this.proxy(function(){this._updatePosition();}));$dialog.on('click{0}'.format(this.eventNamespace),this.closeSelector,this.proxy(function(e){e.preventDefault();this.close();}));if(this.maskClose){this.$mask.on('click{0}'.format(this.eventNamespace),this.proxy(function(){this.close();}));}
    $dialog.on('click{0}'.format(this.eventNamespace),'.J_fmu_dl_confirmed',this.proxy(function(ev){var $this=$(ev.target);$this.attr("disabled",true);this.close();this.confirmHandler();$this.removeAttr("disabled");}));$.each('onBeforeLoad,onLoad,onBeforeClose,onClose'.split(','),this.proxy(function(i,name){if($.isFunction(this[name])){$dialog.on(name,this[name]);}}));$dialog.data('dialog',this);},getContent:function(){return this.$dialog.find(".fmu-dl-content");},getDialog:function(){return this.$dialog;},_step:function(reset){var self=this;var $stepCon=self.$dialog.find(self.stepContainerSelector);if(reset){$stepCon.hide();$stepCon.eq(0).show();return;}
    $stepCon.each(function(){var $curStep=$(this);$curStep.find(self.goNextStepSelector).on('click{0}'.format(self.eventNamespace),function(){var goStepIndex=parseInt($(this).data('gonext'));if(!goStepIndex){console.info('请正确写上data-gonext的值，只支持正整数');return;}
        $curStep.hide();$stepCon.eq(goStepIndex-1).show();self._updatePosition();});});},_buildDefaultTemplate:function(){var defaultTemplate=new StringBuilder();defaultTemplate.append('<section class="fmu-dl-wrap fmu-dl-default-wrap" style="display:none">').append('<div class="fmu-dl-content">default</div>').append('<div class="fmu-dl-btns">').append('<button class="J_fmu_dl_close">确定</button>').append('</div>').append('</section>');this.$dialog=$(defaultTemplate.toString()).appendTo("body");},_buildDefaultTwoTemplate:function(){var defaultTemplate=new StringBuilder();defaultTemplate.append('<section class="fmu-dl-wrap fmu-dl-default-wrap fmu-dl-defaulttwo-wrap" style="display:none">').append('<div class="fmu-dl-content">default two</div>').append('<div class="fmu-dl-btns">').append('<button class="J_fmu_dl_close">取消</button><button class="J_fmu_dl_confirmed">确定</button>').append('</div>').append('</section>');this.$dialog=$(defaultTemplate.toString()).appendTo("body");},_updatePosition:function(){var $win=$(window);var w=$win.width(),h=$win.height(),$dialog=this.$dialog,oWidth=$dialog.outerWidth(true),oHeight=$dialog.outerHeight(true);var lastH,lastW;switch(this.position){case'top':lastH=0;lastW=(w-oWidth)/2;break;case'bottom':lastH=h-oHeight;lastW=(w-oWidth)/2;break;case'center':default:lastH=(h-oHeight)/2;lastW=(w-oWidth)/2;break;}
    var lastH,lastW;switch(this.position){case'top':lastH=0;lastW=(w-oWidth)/2;break;case'bottom':lastH=h-oHeight;lastW=(w-oWidth)/2;break;case'center':default:lastH=(h-oHeight)/2;lastW=(w-oWidth)/2;break;}
    $dialog.css({top:lastH,left:lastW});},updatePosition:function(){this._updatePosition();},load:function(e){if(this.opened){return this;}
    var $dialog=this.$dialog;var $mask=this.$mask;var startProp,endProp;e=e||$.Event();e.type="onBeforeLoad";$dialog.trigger(e);if(e.isDefaultPrevented()){return;}
    this._updatePosition();if(this.animation==true){switch(this.position){case'top':startProp={'-webkit-transform':'translateY(-100%)'};endProp={'-webkit-transform':'translateY(0)'};break;case'bottom':startProp={'-webkit-transform':'translateY(100%)'};endProp={'-webkit-transform':'translateY(0)'};break;case'center':default:startProp={'-webkit-transform':'translateX(-200%)'};endProp={'-webkit-transform':'translateX(0)'};break;}
        $dialog.show().css(startProp).css("-webkit-transition","all 1s ease-in-out")
        setTimeout(function(){$dialog.css(endProp);},0)}else{$dialog.show();}
    $mask.show();this.opened=true;$dialog.trigger('onLoad');if(this.autoClose){setTimeout(this.proxy(function(){this.close();}),this.autoClose);}},close:function(e){var $dialog=this.$dialog;if(this.opened==false||$dialog.is(':hidden')){return;}
    var $mask=this.$mask;$dialog.trigger('onBeforeClose');$dialog.hide();$mask.hide();this._step(true);$dialog.trigger('onClose');this.opened=false;}});;(function(){FLNS.register("Fanli.WebApp.NativeApi");window["nativeTakePhotoCallback"]=function(result,url,ud){};Fanli.WebApp.NativeApi.add("takePhoto",function(options){var settings=$.extend(true,{},{imgMaxWidth:640,uploadUrl:"{0}xiaozu/ajaxUploadImg".format(currentApiRoot),userData:"",t:0,callback:"nativeTakePhotoCallback"},options);var protocol="ifanli://{0}/dev/takephoto?cb={1}&w={2}&ud={3}&upload={4}&t={5}".format(ifanliProtocol,rebuildCallback(settings.callback),settings.imgMaxWidth,settings.userData,encodeURIComponent(settings.uploadUrl),settings.t);connectApp(protocol);});window["nativeLoginCallback"]=function(status,uid,verify_code){};Fanli.WebApp.NativeApi.add("login",function(options){var settings=$.extend(true,{},{userdata:"",callback:"nativeLoginCallback"},options);var param=[];if(settings.userdata&&settings.userdata!=""){param.push("cd="+settings.userdata);}
    if(settings.callback&&settings.callback!=""){param.push("cb="+rebuildCallback(settings.callback));}
    var protocol="ifanli://{0}/app/login".format(ifanliProtocol)+(param.length>0?("?"+param.join("&")):"");connectApp(protocol);});Fanli.WebApp.NativeApi.add("transession",function(){var protocol="ifanli://{0}/app/action/transession".format(ifanliProtocol);connectApp(protocol);});Fanli.WebApp.NativeApi.add("logout",function(options){var protocol="ifanli://{0}/app/logout".format(ifanliProtocol);connectApp(protocol);Fanli.WebApp.NativeApi.transession();});Fanli.WebApp.NativeApi.add("closeWebview",function(options){var protocol="ifanli://{0}/app/action/closewv".format(ifanliProtocol);connectApp(protocol);});window["nativeShareCallback"]=function(result,target,cd){};Fanli.WebApp.NativeApi.add("share",function(options){var defaultImg=typeof document.images[0]=='undefined'?'http://static2.51fanli.net/common/images/webapp/dockicon.png':document.images[0].src;var defaultTitle=document.title;var defaultUrl=window.location.href;var settings=$.extend({type:1,img:defaultImg,content:"",title:defaultTitle,url:defaultUrl,cd:"",target:"wx_session",callback:"nativeShareCallback"},options);var param=[];var protocol;var shareImg=settings.img||defaultImg;var shareTitle=settings.title||defaultTitle;var shareUrl=settings.url||defaultUrl;var shareContent=settings.content||shareTitle;param.push('type='+settings.type);param.push('target='+settings.target);param.push('img='+encodeURIComponent(shareImg));param.push('content='+encodeURIComponent(shareContent));param.push('title='+encodeURIComponent(shareTitle));param.push('url='+encodeURIComponent(shareUrl));param.push('cd='+settings.cd);param.push('cb='+rebuildCallback(settings.callback));protocol="ifanli://{0}/app/share?{1}".format(ifanliProtocol,param.join('&'));connectApp(protocol);});Fanli.WebApp.NativeApi.add("openNewWebview",function(options){if(Device.Utility.Browser.versions.fanliapp){$(document).on('click.IFANLI','a[target=newwebview]',function(e){e.preventDefault();var $this=$(this);var href=encodeURIComponent($this.attr('href'));var urlParam=[];var ifanliHref;urlParam.push('url='+href);urlParam.push('wb=2');ifanliHref='ifanli://{0}/app/show/web?'.format(ifanliProtocol)+urlParam.join('&');connectApp(ifanliHref);});}});$(function(){Fanli.WebApp.NativeApi.openNewWebview();});Fanli.WebApp.NativeApi.add("copy",function(options){var settings=$.extend({content:"",url:location.href},options);var param=[];var protocol;param.push('target='+"copy");param.push('content='+encodeURIComponent(settings.content));param.push('url='+encodeURIComponent(settings.url));protocol="ifanli://{0}/app/share?type=1&{1}".format(ifanliProtocol,param.join('&'))
    connectApp(protocol);});function connectApp(protocol){var iframe=document.createElement("iframe");var iframeStyle=document.createAttribute("style");var iframeSrc=document.createAttribute("src");iframeStyle.nodeValue="display:none;width:0;height:0;";iframeSrc.nodeValue=protocol;iframe.setAttributeNode(iframeStyle);iframe.setAttributeNode(iframeSrc);document.body.appendChild(iframe);setTimeout(function(){document.body.removeChild(iframe);},250);}
    function rebuildCallback(cb){var t=cb;if($.isFunction(cb)){t="fanliHybrid_"+(+new Date());window[t]=function(){cb.apply(null,Array.prototype.slice.call(arguments,0));delete window[t];}}
        return t;}}());;(function(FWW){var $document=$(document);var bindNativeEvent=false;var $curTrigger;var fmuDialog;var isIncludeJquery=typeof(jQuery)!='undefined';FWW.add("Share",function(options){var settings=$.extend(true,{type:"all",needDialog:true,statusDialog:true,triggerSelector:".J_wechat_share_btn",beforeShare:function(){}},options);var DASB=new StringBuilder();var isAll=settings.type=="all";var needDialog=settings.needDialog;var shareListSelector="#J_wechat_share_list";function setup(){buildSharePopHtml();bindShareDialog();bindLiveEvent();}
    function buildSharePopHtml(){if(needDialog&&!$(shareListSelector).length){DASB.append('<style>').append('.wechat-share-dialog .ui-dialog-content{padding:0;}').append('.wechat-share-dialog .ui-dialog-btns{display:none;}').append('.wechat-share-dialog li{margin:0 10px; line-height:42px; border-bottom:1px solid #CCC;}').append('.wechat-share-dialog li:last-child{border:none;}').append('.wechat-share-dialog li a{display:block; padding:10px 0 10px 20px;}').append('.wechat-share-dialog li a:before{content:" "; display:inline-block; width:40px; height:40px; margin-right:15px; vertical-align:middle; background:url(http://static2.51fanli.net/webapp/images/share/icon-share.png) no-repeat; background-size:auto 40px;}').append('.wechat-share-dialog .timeline:before{background-position:-42px 0;}').append('.wechat-share-dialog .friend:before{background-position:0 0;}').append('.fl-hairlines .wechat-share-dialog li{border-width:0.5px;}').append('</style>');DASB.append('<ul id="J_wechat_share_list" style="display:none; width:270px; min-height:125px;">').append('<li class="J_group_row"><a class="J_share_btn timeline three" data-target="wx_timeline" href="javascript:void(0);">分享到朋友圈</a></li>').append('<li class="J_friend_row"><a class="J_share_btn friend three" data-target="wx_session" href="javascript:void(0);">邀请微信好友</a></li>').append('</ul>');$("body").append(DASB.toString());}}
    function bindShareDialog(){if(needDialog){if(isIncludeJquery){fmuDialog=new FMU.UI.Dialog();fmuDialog.$dialog=$(shareListSelector);fmuDialog.maskClose=true;fmuDialog.setup();$(shareListSelector).addClass('wechat-share-dialog fmu-dl-wrap');}
    else{$(shareListSelector).dialog({width:270,autoOpen:false,maskClick:function(){$(shareListSelector).dialog('close');}}).parents('.ui-dialog').addClass('wechat-share-dialog');}}}
    function bindLiveEvent(){$document.on("click",settings.triggerSelector,function(ev){ev.preventDefault();var $this=$(this);if(needDialog){$curTrigger=$this;settings.beforeShare($this);if(isIncludeJquery){fmuDialog.load();}else{$(shareListSelector).dialog("open");}
        resetDialogBtn($this);}else{settings.beforeShare($this);bindNativeApiShare($this);}});if(settings.needDialog){if(bindNativeEvent){return;}
        $document.on("click.WECHATSHARE",".J_share_btn",function(ev){ev.preventDefault();var $this=$(this);bindNativeApiShare($curTrigger,$this);if(isIncludeJquery){fmuDialog.close();}else{$(shareListSelector).dialog("close");}});bindNativeEvent=true;}}
    function resetDialogBtn($trigger){var $dialogWrap=$(shareListSelector);var dialogspm=$trigger.data("dialogspm")?$trigger.data("dialogspm").split(","):["",""];if(settings.type=="group"){$dialogWrap.find(".J_group_row").show();$dialogWrap.find(".J_friend_row").hide();}else if(settings.type=="friend"){$dialogWrap.find(".J_group_row").hide();$dialogWrap.find(".J_friend_row").show();}else{$dialogWrap.find("li").show();}
        $dialogWrap.find(".J_share_btn").data("cd",$trigger.data("cd")).data("img",$trigger.data("img")).data("url",$trigger.data("url")).data("title",$trigger.data("title")).data("content",$trigger.data("content"));if(dialogspm.length>1){$dialogWrap.find(".J_group_row .J_share_btn").data("spm",dialogspm[0]);$dialogWrap.find(".J_friend_row .J_share_btn").data("spm",dialogspm[1]);}else{$dialogWrap.find(".J_share_btn").data("spm",dialogspm[0]);}}
    function bindNativeApiShare($trigger,$shareBtn){Fanli.WebApp.NativeApi.share({'cd':$trigger.data("cd"),'url':$trigger.data("url"),'img':$trigger.data("img"),'title':$trigger.data("title"),'target':$trigger.data("target")?$trigger.data("target"):$shareBtn.data("target"),'content':$trigger.data("content"),'callback':$trigger.data("callback")||"nativeShareCallback"});}
    setup();});})(FLNS.register("Fanli.Webapp.Wechat"));;(function(FHP)
{FHP.add("init",function(){var Toast=Fanli.Utility.Toast;var $p2pWrap=$("#J_p2p_wrap");var $countdown=$('#J_countdown');var $tabBoxLi=$("#J_tab_box").find("li");var $orderTips=$("#J_order_tips");var phoneTipsCookie="p2p_h5_phone_tips";var startTime=parseInt($p2pWrap.data('time'));var endTime=parseInt($p2pWrap.data('end'));var current;var diaConfirm=new FMU.UI.Dialog()
    diaConfirm.render="confirm";diaConfirm.confirmHandler=function(){window.location.href=$(".J_fmu_dl_confirmed").attr("data-href");};var phoneTipsConfirm=new FMU.UI.Dialog()
    phoneTipsConfirm.render="confirm";if(phoneTipsCookie.getCookie()==1){phoneTipsConfirm.onBeforeLoad=function(){$(this).find(".J_fmu_dl_confirmed").text("我要返利").css("color","#f62735");phoneTipsCookie.setCookie("2",1);};phoneTipsConfirm.setup();phoneTipsConfirm.getContent().html("下单了吗？<br/>下单后填写手机号返利才能到账哦！").css("text-align","center");phoneTipsConfirm.confirmHandler=function(){window.location.href="/p2p_1510301/bindphone";};phoneTipsConfirm.load();}
    $.ajax({url:"{0}ajax/getTime".format(currentApiRoot),dataType:'json',success:function(JSON){var timestamp=JSON.data.timestamp;if(timestamp<startTime){diaConfirm.onBeforeLoad=function(){$(this).find(".J_fmu_dl_confirmed").text("先去看看");};diaConfirm.setup();diaConfirm.getContent().html("10月30日下单才有额外返利哦！").css("text-align","center");current=1;alertPop();}
    else if(endTime>timestamp){diaConfirm.onBeforeLoad=function(){$(this).find(".J_fmu_dl_confirmed").text("记住啦");};diaConfirm.setup();diaConfirm.getContent().html("记得回来拿返利哦！").css("text-align","center");current=2;$countdown.data("remain",endTime-timestamp)
        var p2pCd=new FMU.UI.Countdown();var p2pRewardCookie="p2p_reward_cookie";p2pCd.$output=$("#J_countdown");p2pCd.type="all";p2pCd.onExpiry=function(){$countdown.hide();};p2pCd.setup();$countdown.show();if(p2pRewardCookie.getCookie()!=1){$.getJSON("//huodong{0}/p2p_1510301/ajaxUserSubscribe/?type=2&jsoncallback=?".format(currentRootDomain),function(res){if(res.status==1){p2pRewardCookie.setCookie("1",1);$orderTips.show();}});}
        else{$orderTips.show();}
        alertPop();}}});function alertPop(){$(document).on("click",".J_product_url",function(){var $this=$(this);var tips=$this.closest(".J_product_box").data("tips");$(".J_fmu_dl_confirmed").attr("data-href",$(this).attr("data-href"));if(phoneTipsCookie.getCookie()!=2){phoneTipsCookie.setCookie("1",1);}
        if(current==2){diaConfirm.getContent().html("<span style='font-size:18px;'>记得回来拿返利哦！<span><br/><span class='red' style='font-size:14px;'>{0}</span>".format(tips)).css("text-align","center");}
        diaConfirm.load();});}
    $tabBoxLi.on("click",function(){var $this=$(this);var index=$this.index();$tabBoxLi.removeClass("cur");$this.addClass("cur");window.scrollTo(0,$(".J_p2p_products").eq(index).offset().top-50);});wxShare();function wxShare(){var min=100;var $window=$(window);var winHeight=$window.height();var $sidebarWrap=$("#J_sidebar");var $gotopBtn=$sidebarWrap.find(".J_gotop_trigger");var $wechatBtn=$sidebarWrap.find(".J_wechat_share_btn");function setup(){bindScroll();bindGotop();bindWechatShare();}
        function bindScroll(){var startTop=$window.scrollTop();var tid;$window.on('scroll.SHARE',function(){$wechatBtn.css('display','block');});$window.on('scroll.SIDEBAR',function(){clearTimeout(tid);tid=setTimeout(function(){var endTop=$window.scrollTop();if(startTop-endTop>80&&endTop>min){$gotopBtn.css('display','block');}
        else{$gotopBtn.hide();}
            startTop=endTop;},100);});}
        function bindGotop(){$gotopBtn.on("click",function(){window.scrollTo(0,1);});}
        function bindWechatShare(){if($wechatBtn.length){Fanli.Webapp.Wechat.Share();}}
        setup();}}).init();}(FLNS.register("Fanli.HuoDong.P2pp1510301")));