CREATE TABLE keywords (
    key_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    par_id INT UNSIGNED NOT NULL,
    word VARCHAR(100) DEFAULT '',
    url VARCHAR(300) DEFAULT '',
    PRIMARY KEY (key_id)
    date_entered TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=MyISAM DEFAULT Charset=UTF8;